config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :url_links
  resources :views, path: :v, only: [:show]
  root "url_links#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/metadata.rb
require "open-uri"
class Metadata
  attr_reader :doc

  def self.retrieve_from(url)
    new(URI.open(url))
    rescue
      new
  end

  def initialize(html=nil)
    @doc = Nokogiri::HTML(html)
  end

  def attributes
    {
      title: title,
      description: description,
      image: image
    }
  end

  def title
    doc.at_css("title")&.text
  end

  def description
    meta_tag_content "description"
  end

  def image
    meta_tag_content "og:image", name_attribute: :property
  end

  def meta_tag_content(name, name_attribute: :name)
    doc.at_css("meta[#{name_attribute}='#{name}']")&.attributes&.fetch("content", nil)&.text
  end
end

app/models/short_code.rb
class ShortCode
  ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ".freeze
  BASE = ALPHABET.length

  def self.encode(number)
    return ALPHABET.first if number.zero? || number.nil?
    result = ""

    while number > 0 do
      index = number % BASE
      char = ALPHABET[index]
      result.prepend char
      number = number / BASE
    end

    result
  end
  def self.decode(string)
    number = 0
    string.reverse.each_char.with_index do |char, index|
      power = BASE**index
      index = ALPHABET.index(char)
      number += index * power
    end

    number
  end
end

app/models/url_link.rb
class UrlLink < ApplicationRecord
  belongs_to :user, optional: true
  has_many :views, dependent: :destroy
  scope :recent_first, -> {order(created_at: :desc)}

  validates :url, presence: true

  after_save_commit if: :url_previously_changed? do
    MetadataJob.perform_later(to_param)
  end

  def self.find_by_short_code(code)
    find ShortCode.decode(code)
  end

  def to_param
    ShortCode.encode(id)
  end

  def domain
    URI(url).host rescue URI::InvalidURIError
  end

  def editable_by?(user)
    user_id? && (user_id == user&.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :url_links
end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :url_link, counter_cache: :view_count
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend

  def set_link
    @url_link = UrlLink.find_by_short_code(params[:id])
  end
end

app/controllers/url_links_controller.rb
class UrlLinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :check_if_editable, only: [:edit, :update, :destroy]

  def index
    @pagy, @url_links = pagy UrlLink.recent_first
    @url_link ||= UrlLink.new
    rescue Pagy::OverflowError
      redirect_to root_path
      #params[:page] = 1
      #retry
  end

  def create
    @url_link = UrlLink.new(url_link_params.with_defaults(user: current_user))
    if @url_link.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.turbo_stream {render turbo_stream: [
          turbo_stream.prepend("links", @url_link),
          turbo_stream.replace("link_form", partial: "url_links/form", locals: {url_link: UrlLink.new})
        ]}
      end

    else
      index
      render :index, status: :unprocessable_entity
    end
  end

  def edit

  end
  def show

  end
  def update
    if @url_link.update(url_link_params)
      redirect_to @url_link
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @url_link.destroy
    redirect_to root_path, notice: "Link has been deleted"
  end

  private

  def url_link_params
    params.require(:url_link).permit(:url)
  end

  def check_if_editable
    unless @url_link.editable_by?(current_user)
      redirect_to @url_link, alert: "You aren't allowed to do that."
    end
  end

end

app/controllers/views_controller.rb
class ViewsController < ApplicationController
  before_action :set_link

rescue_from ActiveRecord::RecordNotFound do
  redirect_to root_path, alert: "Missing link!"
end

  def show
    @url_link.views.create(ip: request.ip, user_agent: request.user_agent)
    redirect_to @url_link.url, allow_other_host: true
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

end

app/helpers/favicon_helper.rb
module FaviconHelper
  def favicon_image_tag(domain, **kwargs)
    image_tag google_favicon_url(domain), **kwargs
  end
  def google_favicon_url(domain)
    "https://www.google.com/s2/favicons?domain=#{domain}"
  end
end

app/helpers/url_shortener_helper.rb
module UrlShortenerHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShortener</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main>
      <%= tag.p notice, class:"notice" if notice %>
      <%= tag.p alert, class:"alert" if alert %>
      <div class="nav">
        <h1><%= link_to "Url Shortener", root_path %></h1>
        <div class="login">
          <% if user_signed_in? %>
            <%= link_to "Profile", edit_user_registration_path %>
            <%= button_to "Logout", destroy_user_session_path, class: "btn", method: :delete %>
          <% else %>
            <%= link_to  "Sign Up", new_user_registration_path %>
            <%= link_to  "Login", new_user_session_path, class: "btn" %>
          <% end %>
        </div>
      </div>
    </div>
    <%= yield %>
  </main>
</body>
</html>

app/views/url_links/_form.html.erb
<%= form_with model: url_link, id: "link_form" do |form| %>
  <div>
    <%= form.url_field :url, required: true, autofocus: true, placeholder: "https://example.com" %>
    <%= form.submit "Save" %>
  </div>
<% end %>

app/views/url_links/_url_link.html.erb
<%= tag.div id: dom_id(url_link) do %>
  <%= turbo_stream_from url_link %>
  <div class="link-grid" >
    <div class="link-url">
      <%= link_to view_path(url_link), target: :_blank, data: {turbo: false} do %>
        <%= favicon_image_tag url_link.domain, class: "link-domain" %>
        <%= url_link.title || url_link.url %>
        <%= tag.div url_link.description, class: "link-description" %>
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
        </svg>
      <% end %>
    </div>
    <div class="link-views" >
      <%= link_to pluralize(url_link.view_count, "views"), url_link %>
    </div>
    <div class="link-copy" >
      <%= button_tag "Copy", class: "link-copy-btn", data: {controller: "clipboard", clipboard_text: view_url(url_link) } %>
    </div>
  </div>
<% end %>

app/views/url_links/edit.html.erb
<h1>Edit Link</h1>
<%= render partial: 'form', locals: {url_link: @url_link} %>
<div class="edit-links" >
  <%= link_to 'Cancel', @url_link %>
  or
  <%= button_to "Delete", @url_link, method: :delete, data: {turbo_confirm: "Are you sure"} %>
</div>

app/views/url_links/index.html.erb
<%= render partial: "form", locals: {url_link: @url_link } %>
<div id="links">
  <%= render @url_links %>
  <% if @pagy.pages > 1 %>
    <div class="pagination">
      <%== pagy_nav @pagy %>
    </div>
  <% end %>
</div>

app/views/url_links/new.html.erb
<h1>New URL Link</h1>

app/views/url_links/show.html.erb
<div class="flex">
  <%= link_to '← Back to all links', root_path %>
  <div class="links">
    <%= tag.div pluralize(@url_link.view_count, "view")%>
    <div class="link-copy" >
      <%= button_tag "Copy", class: "link-copy-btn", data: {controller: "clipboard", clipboard_text: view_url(@url_link) } %>
      <%= link_to 'Edit',  edit_url_link_path(@url_link), class: "link-copy-btn" if @url_link.editable_by?(current_user) %>
    </div>
  </div>
</div>
<h1><%= @url_link.url %></h1>
<%= tag.div @url_link.description %>
<div class="link-graph">
  <%= link_to view_path(@url_link), target: :_blank, data: {turbo: false} do %>
    <%= image_tag "https://www.google.com/s2/favicons?domain=#{@url_link.domain}"%>
    <%= truncate @url_link.url %>
    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor">
      <path stroke-linecap="round" stroke-linejoin="round" d="M13.5 6H5.25A2.25 2.25 0 003 8.25v10.5A2.25 2.25 0 005.25 21h10.5A2.25 2.25 0 0018 18.75V10.5m-10.5 6L21 3m0 0h-5.25M21 3v5.25" />
    </svg>
  <% end %>
</div>
<%= line_chart @url_link.views.group_by_day(:created_at, range: 2.weeks.ago..Time.now, expand_range: true ).count %>